import { verifyProofLocal, type LocalProofResult } from 'invinoveritas-verify'
import {
  BaseError,
  ContractFunctionRevertedError,
  createPublicClient,
  http,
  type Address,
  type Hex,
} from 'viem'
import { foundry } from 'viem/chains'
import { agentWorkflowAbi } from '../../execution/ERC8301/abi.js'
import type {
  AgentReplyTuple,
  AgentWorkflowGateConfig,
  ReplyAnchorStatus,
  ReviewGateConfig,
  ReviewOptions,
  ReviewResponse,
} from './types.js'

const DEFAULT_BASE_URL = 'https://api.babyblueviper.com'

/**
 * A pre-action judgment gate: call `review()` with a proposed action before
 * an agent executes it, get back a verdict (approve / reject /
 * approve_with_concerns) plus a signed proof you verify yourself — never a
 * bare "trust me" boolean.
 *
 * This is deliberately NOT tied to an agent-ercs interface. invinoveritas's
 * `/review` is a plain off-chain HTTP judgment service, not an on-chain
 * contract, so it doesn't fit the `<category>/<ERCXXXX>` generation pattern
 * the rest of this SDK follows — see README.md in this directory for why
 * it's hand-written rather than generated by `/add-erc`.
 */
export class ReviewGateClient {
  private readonly apiKey: string
  private readonly baseUrl: string

  constructor(config: ReviewGateConfig) {
    this.apiKey = config.apiKey
    this.baseUrl = (config.baseUrl ?? DEFAULT_BASE_URL).replace(/\/$/, '')
  }

  /**
   * Get a verdict on a proposed action before it executes.
   *
   * @param artifact - The proposed action, as text: a shell command, a code
   *   diff, an order description — whatever the agent is about to do.
   * @param options - Optional artifact type, extra context, and whether to
   *   request a signed proof (default true).
   */
  async review(artifact: string, options: ReviewOptions = {}): Promise<ReviewResponse> {
    const body: Record<string, unknown> = {
      artifact,
      sign: options.sign ?? true,
    }
    if (options.artifactType) body.artifact_type = options.artifactType
    if (options.context) body.context = options.context

    const res = await fetch(`${this.baseUrl}/review`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify(body),
    })

    if (!res.ok) {
      const detail = await res.text().catch(() => '')
      throw new Error(`invinoveritas /review returned ${res.status}: ${detail.slice(0, 500)}`)
    }

    return (await res.json()) as ReviewResponse
  }

  /**
   * Independently verify a review response's signed proof — a pure,
   * offline recompute via `invinoveritas-verify` (BIP-340 Schnorr over the
   * NIP-01 event id, checked against invinoveritas's published pubkey).
   * No network call, no trust in this client or in invinoveritas's own
   * infrastructure: this is the same check anyone else can run against the
   * bytes alone.
   *
   * @param response - A `ReviewResponse` from `review()` that was called
   *   with `sign: true` (the default).
   * @throws if the response has no `proof.event` to verify (it was called
   *   with `sign: false`).
   */
  verifyLocal(response: ReviewResponse): LocalProofResult {
    if (!response.proof?.event) {
      throw new Error(
        'No signed event on this response — call review() with sign:true (the default) to get a verifiable proof.',
      )
    }
    return verifyProofLocal(response.proof.event as unknown as Record<string, unknown>)
  }

  /**
   * Confirm on-chain whether a review's downstream action actually reached
   * an ERC-8301 `IAgentWorkflow` gate — closes a real gap: `review()` and
   * `verifyLocal()` only prove what invinoveritas SAID about an action, not
   * that the action's on-chain reply was ever anchored (an agent could
   * silently drop it before submission, or a workflow could reject it
   * before `onAgentReply` ever ran).
   *
   * Reads `getAgentReply(replyHash)` on the given workflow contract. A
   * revert means the hash was never anchored — ERC-8301's own spec
   * ("MUST revert if replyHash is unknown") makes this the correct signal,
   * not an error condition, so this method returns `{ anchored: false }`
   * for it rather than throwing. Any OTHER failure (bad RPC URL, wrong
   * contract address, network error) is NOT caught here and propagates —
   * conflating "confirmed not anchored" with "couldn't check" would make
   * this method fail open on exactly the case it exists to catch.
   *
   * Note on naming: an earlier draft of ERC-8301 (commit `9fcb78c0c8`)
   * apparently added a dedicated `AgentReplyAnchored` event for this; as of
   * this writing that event is NOT present in `trustless-ai/agent-ercs`'s
   * merged `IAgentWorkflow.sol` (confirmed directly against the interface
   * this SDK's own `execution/ERC8301` module already binds to — replies
   * are anchored via the existing `NewAgentTask` event with `stage=2`, not
   * a separately-named one). `getAgentReply`'s revert-vs-return behavior
   * answers the same question without depending on that event name.
   *
   * @param workflow - `{ rpcUrl, address }` for the deployed IAgentWorkflow
   *   contract the reply would have been submitted to. Read-only — no
   *   wallet/account needed.
   * @param replyHash - The ERC-8301 reply hash to check
   *   (`keccak256(abi.encode(outputHash, timestamp, replier,
   *   keccak256(abi.encodePacked(prevTaskHashes)), workflowRunId))` — see
   *   `computeReplyHash` in `execution/ERC8301/recompute.js` if you need to
   *   derive it from the reply's own fields rather than a value already in
   *   hand from the submission transaction).
   */
  async confirmReplyAnchored(
    workflow: AgentWorkflowGateConfig,
    replyHash: Hex,
  ): Promise<ReplyAnchorStatus> {
    // `workflow.chain` defaults to foundry so local/anvil callers need not supply it, but it is
    // configurable because this method is documented as confirming against the deployed
    // IAgentWorkflow contract generally. The previous hardcode worked only because viem does not
    // enforce chainId on a read-only eth_call -- a property of the call type, not of the code
    // being right. (Tiago Merlini via Echo, PR #22 review.)
    const publicClient = createPublicClient({
      chain: workflow.chain ?? foundry,
      transport: http(workflow.rpcUrl),
    })

    try {
      // Typed via a narrow local alias rather than `as never` + a blanket tuple cast. The
      // destructure order below is load-bearing -- getAgentReply returns
      // [reply tuple, verifier, proven, verificationDigest], and the leading hole skips the
      // reply tuple. Echo had to verify that order by hand against ground truth precisely
      // because the old casts disabled the compile-time net; an ABI change or a reordered
      // destructure would have been silent to tsc and wrong at runtime, which is the worst
      // pairing. Keeping the return shape named means tsc catches that drift instead.
      const reply = (await publicClient.readContract({
        address: workflow.address as Address,
        abi: agentWorkflowAbi,
        functionName: 'getAgentReply',
        args: [replyHash],
      } as Parameters<typeof publicClient.readContract>[0])) as AgentReplyTuple

      const [, verifier, proven, verificationDigest] = reply

      return { anchored: true, proven, verifier, verificationDigest }
    } catch (err) {
      const isUnknownReply =
        err instanceof BaseError &&
        err.walk((e) => e instanceof ContractFunctionRevertedError) !== null
      if (isUnknownReply) {
        return { anchored: false }
      }
      throw err
    }
  }
}
